### PR TITLE
fix for free() and simd/sse handling for constraints FrameOffsets

### PR DESCRIPTION
**Pull request by gepa21**

### CODE REVIEW

**Comment by VirusFree** [comment]
quick question..
I had a look at the bulletsharp repo at google ( https://code.google.com/p/bulletsharp/source/list ) and i see the development is still going on there and from a quick look at the commits i got a sense that the code is diverging a bit from here.
Which branch should i be using? 
Are all the branches moving towards a "unified" branch., or are they going to become obsolete and all fixes/features be merged to one branch? ( pinvoke perhaps? )
Thanks.

**Comment by AndresTraks** [comment]
Good question. Prepare for a wall of text. :)

So for background information, there is the C++/CLI version, which has been in development since 2010. It's stable, well tested and generally works well. The downside is that it's tied to Microsoft's development platform. The binaries contain unmanaged code from bullet, so you can't run it under Linux, for example. Mono doesn't have a C++/CLI compiler and will probably never have it, so you can't compile C++/CLI for anything other than x86 and x64 Windows. Since more and more people want to make their games and apps cross-platform, then that's not exactly ideal.

The solution to that is the P/invoke version of BulletSharp created in 2013. This is a fundamentally different approach. The wrapper is split into two parts: a library that contains the platform-specific code (libbulletc.dll) and a fully managed library (BulletSharp.dll) that loads the correct platform-specific library at runtime and talks to it via Platform Invoke. This kind of setup works, but is much more complex. For one thing, there is no standard binary interface (ABI) for dynamically loaded C++ libraries, so there is an extra abstraction layer that translates between C++ and C. Secondly, there is no standard way for a .NET library to load another library at runtime depending on the platform. It also hasn't been in development for as long, so I consider it a bit less stable.

The C++/CLI version is being developed on GitHub and P/invoke on Google Code. I consider them equally important for now, but I expect that at some point there will be more interest in P/invoke, since it's cross-platform. Once P/invoke gets more stable and feature-complete (it's quite close already actually) and some of the cross-platform issues are ironed out (not sure about those), then it's possible that C++/CLI will become obsolete and version 3 with the new GPU stuff will be P/Invoke only. This won't be in the near future though. I haven't done detailed benchmarks yet, but P/invoke might be a little bit slower because of the extra abstraction. In that case I'd definitely keep C++/CLI. In practice though, I haven't noticed any difference.

There is also a fully managed (pure C#) version of Bullet for platforms that don't allow any unmanaged code, but the performance is much worse. See also:
https://code.google.com/p/bulletsharp/wiki/SupportedPlatforms

So if you're not targetting anything other than Windows, then C++/CLI will be just fine. Since you have some extensions to bullet in your repositories, I suspect that it would more difficult to maintain them with P/invoke. You'd have to also make changes to libbulletc in addition to bullet and BulletSharp.

The "unification" is about making the C++/CLI and P/Invoke interfaces equivalent so that it would be as easy as possible to switch between the two without having to rewrite parts of your code or encounter some unexpected behaviour. They can't converge completely, because they're fundamentally different approaches. It's clear that P/invoke is here to stay. There is less reason for C++/CLI to stay, but the current plan is to support it for at least a couple more years. It depends on how well P/invoke will do and maybe more importantly, the development rate of bullet 3.

**Comment by VirusFree** [comment]
Thanks, that is a very good answer and very helpful! I appreciate it :)
You also answered some questions that would be my follow-up, like what are the plans for bullet 3.

`Once P/invoke gets more stable and feature-complete..`
I can wait for the P/invoke branch to get a little more mature and then try to integrate it with my project. That way i can help out with testing and fixes.

`There is also a fully managed (pure C#) version of Bullet...`
I saw that project before and had plans to integrate it in my project, but looking at the history https://code.google.com/p/bullet-xna/source/list the last commit was almost a year ago (and any significant progess even older), so it looks dead.

**Comment by VirusFree** [comment]
Yeah, garbage can become a problem in a managed memory world, but it's not as dramatic as people make it to be. I had similar issues with my project (which is a managed game engine) and doing anything at 60+ fps will result in a lot of garbage, but a good object-recycler/object-pool solution can pretty much make the problem disappear. (and memory profiling is extremely helpful)

I would even argue that a good recycling mechanism could be as fast (if not faster) than a generic native allocator (that doesn't use pools behind), since you would still have to allocate/free all the time and that would put stress on the allocator. ( Also i think optimizing an object recycler for multi-thread is easier.)

Hopefully i can find some time and have a look at the bullet-noxna project , but what i REALLY would like to see it is a fully managed GPU accelerated (opencl) physics engine :) :)

**Pull request merged**
